services:
  - type: web
    name: luni-staging
    env: node
    plan: starter
    region: oregon
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: USE_REDIS
        value: "0"
      - key: PORT
        value: "3000"
    healthCheckPath: /health
    autoDeploy: true

